### ISSUE TITLE
Initilization of Sequence::mComplement

### ISSUE THREAD

**Issue by natir** [BIG-Tools/BigBrowser#17]
In Sequence class we use private static c style table. The init of this table is complicate actually we use a static function call in the constructor of Sequence for init this table maybe we can found a better solution to do this.

This issue is her for discuss on potential solution.

**Comment by dridk** [comment]
I wonder how many time you lost when using a dict like QHash instead a vector.

**Comment by natir** [comment]
If we can save time we need save time.

**Comment by natir** [comment]
May be we can use Singleton class for reverse complement.

Advantage :
- complement table create at once
- access form every where

Problem what's the goal of this class, generate reverse complement of Sequence (and inheritance) or generate reverse complement for all class implement operator[] and constructor with this signature constructor(size_t lengt, value) ?

I prefer the second solution because is more generalist, but required some little modification in Sequence.

**Comment by dridk** [comment]
Normally, I will not advise to use singleton for a simple class. But for
your case, if you really want to win some memory,  you are probably right..
a methods called "table" should create the table for the first use.

The goal of Sequence is just to be a containers of a nucleotide sequence
like a string.
And it should provide some methods for convenience.
At the end, i dont think Sequence class will contains lot of nucleotide in
BB. So we don't need right now improve performance.. but maybe the futur
Did you see how other library manage sequence class?
Le 10 mars 2016 18:47, "Pierre Marijon" notifications@github.com a écrit :

May be we can use Singleton class for reverse complement.

Advantage :
- complement table create at once
- access form every where

Problem what's the goal of this class, generate reverse complement of
Sequence (and inheritance) or generate reverse complement for all class
implement operator[] and constructor with this signature constructor(size_t
lengt, value) ?

I prefer the second solution because is more generalist, but required some
little modification in Sequence.

**Comment by natir** [comment]
with 4c1a49d88f5 commit all thing is solve
